/* @flow */

export const NAV_POP = 'NAV_POP';
export const NAV_PUSH = 'NAV_PUSH';
export const NAV_RESET = 'NAV_RESET';

export const CHANGE_COUNTRYCODE = 'CHANGE_COUNTRYCODE';
export const SHOW_DIALCODE_PICKER = 'SHOW_DIALCODE_PICKER';

export const INCOMING_CALL = 'INCOMING_CALL';
export const ACCEPT_INCOMING_CALL = 'ACCEPT_INCOMING_CALL';
export const DECLINE_INCOMING_CALL = 'DECLINE_INCOMING_CALL';
export const END_CALL = 'END_CALL';
export const HIDE_CALL_DIALOG = 'HIDE_CALL_DIALOG';
