/* @flow */

export const NAV_POP = 'NAV_POP';
export const NAV_PUSH = 'NAV_PUSH';
export const NAV_RESET = 'NAV_RESET';

export const CHANGE_COUNTRYCODE = 'CHANGE_COUNTRYCODE';
export const SHOW_DIALCODE_PICKER = 'SHOW_DIALCODE_PICKER';
export const ADD_DIGIT_TO_NUMBER = 'ADD_DIGIT_TO_NUMBER';
export const REMOVE_DIGIT_FROM_NUMBER = 'REMOVE_DIGIT_FROM_NUMBER';
export const CLEAR_NUMBER = 'CLEAR_NUMBER';
export const CONVERT_LAST_DIGIT = 'CONVERT_LAST_DIGIT';

export const INCOMING_CALL = 'INCOMING_CALL';
export const ACCEPT_INCOMING_CALL = 'ACCEPT_INCOMING_CALL';
export const DECLINE_INCOMING_CALL = 'DECLINE_INCOMING_CALL';
export const END_CALL = 'END_CALL';
export const HIDE_CALL_DIALOG = 'HIDE_CALL_DIALOG';
export const MUTE_MICROPHONE = 'MUTE_MICROPHONE';
export const USE_LOUD_SPEAKER = 'USE_LOUD_SPEAKER';
export const SHOW_ONCALL_KEYPAD = 'SHOW_ONCALL_KEYPAD';

export const CHANGE_TEXTFIELD_VALUE = 'CHANGE_TEXTFIELD_VALUE';
export const CHANGE_INPUT_ERROR = 'CHANGE_INPUT_ERROR';
export const SET_LOGIN_LOADING = 'SET_LOGIN_LOADING';
export const RESET_LOGIN_FORM = 'RESET_LOGIN_FORM';

export const SET_INFO_PAGE_INDEX = 'SET_INFO_PAGE_INDEX';

export const SET_AUTH_TOKEN = 'SET_AUTH_TOKEN';

export const RESET = 'RESET';
